import {
  Activity,
  Award,
  Baby,
  Bath,
  Bed,
  Bike,
  Brain,
  Building2,
  CalendarCheck,
  Car,
  ChefHat,
  Clock,
  Coffee,
  Compass,
  Croissant,
  Crown,
  Droplets,
  Dumbbell,
  Eye,
  Facebook,
  Flame,
  Flower2,
  Gem,
  Glasses,
  Hand,
  HeartPulse,
  Instagram,
  Leaf,
  Linkedin,
  MapPin,
  Martini,
  Microscope,
  Moon,
  Music,
  Palette,
  PawPrint,
  Phone,
  Plane,
  Salad,
  Scissors,
  ShieldCheck,
  Smile,
  Sparkles,
  Stethoscope,
  Sun,
  Syringe,
  Truck,
  Twitter,
  Users,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Wine,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons referenced by name from demo configs, so config files stay pure data
 * (no JSX / component imports) and can be edited by non-developers.
 */
export const iconRegistry = {
  activity: Activity,
  award: Award,
  baby: Baby,
  bath: Bath,
  bed: Bed,
  bike: Bike,
  brain: Brain,
  building: Building2,
  calendar: CalendarCheck,
  car: Car,
  chef: ChefHat,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  croissant: Croissant,
  crown: Crown,
  droplets: Droplets,
  dumbbell: Dumbbell,
  eye: Eye,
  facebook: Facebook,
  flame: Flame,
  flower: Flower2,
  gem: Gem,
  glasses: Glasses,
  hand: Hand,
  heart: HeartPulse,
  instagram: Instagram,
  leaf: Leaf,
  linkedin: Linkedin,
  mapPin: MapPin,
  martini: Martini,
  microscope: Microscope,
  moon: Moon,
  music: Music,
  palette: Palette,
  paw: PawPrint,
  phone: Phone,
  plane: Plane,
  salad: Salad,
  scissors: Scissors,
  shield: ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  sun: Sun,
  syringe: Syringe,
  truck: Truck,
  twitter: Twitter,
  users: Users,
  utensils: UtensilsCrossed,
  waves: Waves,
  wifi: Wifi,
  wind: Wind,
  wine: Wine,
  youtube: Youtube,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconRegistry;

/** Falls back to a neutral icon so a config typo never breaks a render. */
export function getIcon(name: string | undefined): LucideIcon {
  if (name && name in iconRegistry) {
    return iconRegistry[name as IconKey];
  }
  return Sparkles;
}
