import { salonMedia as m } from '@/config/media';
import type { DemoConfig } from '@/types/demo';

/**
 * LUMÉ BEAUTY — luxury salon & skin studio.
 * Identity: fashion editorial. Bone paper, bronze, oversized italic serif.
 */
export const salonDemo: DemoConfig = {
  slug: 'salon',
  businessName: 'Lumé Beauty',
  logoMark: 'L',
  industry: 'Beauty Salon',
  tagline: 'Beauty, edited.',

  seo: {
    title: 'Lumé Beauty — Hair, Skin & Beauty Studio',
    description:
      'Lumé Beauty is a luxury hair, skin and nail studio offering colour, facials, lashes and membership treatments with instant online booking.',
    keywords: ['beauty salon', 'hair salon', 'facial', 'lashes', 'manicure', 'spa'],
  },

  card: {
    title: 'Beauty Salon',
    description:
      'An editorial, image-led salon site with treatment menus, artist profiles, membership tiers and booking.',
    features: ['Editorial layout', 'Treatment menu', 'Membership tiers', 'Artist booking'],
    ctaLabel: 'View Salon Demo',
    image: m.hero,
    accent: '#A9765A',
  },

  theme: {
    mode: 'light',
    brand: '#A9765A',
    brandSoft: '#EFE4DA',
    brandContrast: '#FFFFFF',
    accent: '#2A211C',
    bg: '#F4EFE9',
    surface: '#FBF8F5',
    surfaceAlt: '#E9E0D6',
    ink: '#1B1512',
    inkMuted: '#6F625A',
    line: '#DCD0C4',
    radius: '2px',
    radiusLg: '4px',
    displayFont: 'var(--font-cormorant)',
    bodyFont: 'var(--font-inter)',
    displayStyle: 'italic',
  },

  nav: [
    { label: 'Studio', href: '#about' },
    { label: 'Services', href: '#services' },
    { label: 'Treatments', href: '#treatments' },
    { label: 'Artists', href: '#team' },
    { label: 'Gallery', href: '#gallery' },
    { label: 'Membership', href: '#membership' },
  ],

  cta: { label: 'Book Your Treatment', short: 'Book' },

  contact: {
    phone: '+44 20 7946 0311',
    email: 'studio@lumebeauty.demo',
    addressLines: ['14 Marlowe Yard, Off Redchurch Street', 'Shoreditch, London E2 7DP'],
    mapHint: 'Courtyard entrance · Five minutes from Shoreditch High Street',
    socials: [
      { label: 'Instagram', icon: 'instagram' },
      { label: 'Facebook', icon: 'facebook' },
      { label: 'YouTube', icon: 'youtube' },
    ],
  },

  hours: {
    0: { open: '11:00', close: '17:00' },
    1: null,
    2: { open: '10:00', close: '19:00' },
    3: { open: '10:00', close: '20:00' },
    4: { open: '10:00', close: '21:00' },
    5: { open: '09:00', close: '20:00' },
    6: { open: '09:00', close: '18:00' },
  },

  booking: {
    mode: 'appointment',
    steps: ['service', 'staff', 'date', 'time', 'details', 'confirm'],
    slotMinutes: 30,
    leadTimeHours: 2,
    horizonDays: 60,
    currency: 'GBP',
    currencySymbol: '£',
    dateMode: 'single',
    labels: {
      service: 'Treatment',
      servicePlural: 'Choose a treatment',
      staff: 'Artist',
      staffPlural: 'Choose your artist',
      date: 'Date',
      time: 'Time',
      guests: 'Guests',
      customer: 'Your details',
      submit: 'Confirm booking',
      successTitle: 'Booking confirmed',
      successText:
        'Your artist has been notified. We hold your chair for 15 minutes — a card is never charged in advance.',
    },
    notesPlaceholder: 'Inspiration, allergies, previous colour history…',
  },

  services: [
    {
      id: 'colour',
      name: 'Colour & Balayage',
      description:
        'Hand-painted, lived-in colour built to grow out beautifully. Includes gloss, cut and finish.',
      durationMin: 180,
      price: 240,
      priceFrom: true,
      icon: 'palette',
      image: m.s1,
      badge: 'Signature',
      highlights: ['Free colour consultation', 'Bond-building treatment', 'Gloss & finish included'],
      staffIds: ['isla', 'juno'],
    },
    {
      id: 'cut',
      name: 'Precision Cut & Style',
      description:
        'A cut designed around how your hair actually falls, finished with a lesson in keeping it that way.',
      durationMin: 75,
      price: 95,
      icon: 'scissors',
      image: m.g5,
      highlights: ['Dry consultation first', 'Wash & scalp ritual', 'Styling lesson'],
      staffIds: ['isla', 'juno', 'talia'],
    },
    {
      id: 'facial',
      name: 'Signature Facial',
      description:
        'Ninety minutes of deep cleanse, enzyme resurfacing, LED and lymphatic massage. You will float out.',
      durationMin: 90,
      price: 150,
      icon: 'sparkles',
      image: m.s3,
      badge: 'Most booked',
      highlights: ['Skin analysis', 'LED therapy', 'Take-home protocol'],
      staffIds: ['talia', 'mira'],
    },
    {
      id: 'nails',
      name: 'Luxury Manicure',
      description:
        'Russian-technique manicure with a mirror finish that survives three weeks of real life.',
      durationMin: 60,
      price: 68,
      icon: 'hand',
      image: m.s2,
      highlights: ['Russian technique', 'Hand & arm massage', '3-week wear'],
      staffIds: ['mira', 'juno'],
    },
    {
      id: 'massage',
      name: 'Deep Tissue Ritual',
      description:
        'Warm oil, slow pressure, and a therapist who finds the knot you did not mention.',
      durationMin: 60,
      price: 110,
      icon: 'waves',
      image: m.s4,
      highlights: ['Warm oil ritual', 'Aromatherapy blend', 'Quiet room'],
      staffIds: ['mira'],
    },
    {
      id: 'makeup',
      name: 'Editorial Makeup',
      description:
        'Camera-ready or barely-there, built on skin prep rather than layers of product.',
      durationMin: 60,
      price: 130,
      icon: 'gem',
      image: m.s5,
      highlights: ['Skin-first prep', 'Lash application', 'Touch-up kit'],
      staffIds: ['talia', 'juno'],
    },
    {
      id: 'brows',
      name: 'Brows & Lashes',
      description:
        'Brow shaping, lamination and lash lifts mapped to your face rather than a template.',
      durationMin: 45,
      price: 75,
      icon: 'eye',
      image: m.s6,
      highlights: ['Brow mapping', 'Lamination', 'Tint included'],
      staffIds: ['talia', 'mira'],
    },
    {
      id: 'bridal',
      name: 'Bridal Package',
      description:
        'Trial, day-of hair and makeup, and a calm room that belongs only to you and your people.',
      durationMin: 180,
      price: 520,
      priceFrom: true,
      icon: 'crown',
      image: m.about,
      highlights: ['Full trial included', 'Private suite', 'Travel available'],
      staffIds: ['isla', 'talia'],
    },
  ],

  staff: [
    {
      id: 'isla',
      name: 'Isla Moreau',
      role: 'Creative Director · Colour',
      bio: 'Fifteen years between Paris and London, four of them on fashion week backstage crews. Isla’s colour work is the reason half our clients travel in.',
      image: m.p1,
      tags: ['Balayage', 'Editorial'],
      rating: 5,
      experienceYears: 15,
      workdays: [2, 3, 4, 5, 6],
    },
    {
      id: 'juno',
      name: 'Juno Adeyemi',
      role: 'Senior Stylist',
      bio: 'Specialist in curls and textured hair, with a following built almost entirely on people showing friends the back of their head.',
      image: m.p2,
      tags: ['Textured hair', 'Cutting'],
      rating: 4.9,
      experienceYears: 9,
      workdays: [0, 3, 4, 5, 6],
    },
    {
      id: 'talia',
      name: 'Talia Brenner',
      role: 'Head of Skin & Makeup',
      bio: 'Aesthetician turned makeup artist. Talia treats makeup as the last five percent — the first ninety-five is skin.',
      image: m.p3,
      tags: ['Facials', 'Makeup'],
      rating: 5,
      experienceYears: 12,
      workdays: [2, 3, 4, 5, 6],
    },
    {
      id: 'mira',
      name: 'Mira Halvorsen',
      role: 'Therapist · Nails & Body',
      bio: 'Trained in Oslo and Bangkok. Mira’s manicures last three weeks and her massages are quietly, unreasonably good.',
      image: m.p4,
      tags: ['Nails', 'Massage'],
      rating: 4.9,
      experienceYears: 8,
      workdays: [0, 2, 3, 4, 5],
    },
  ],

  sections: [
    {
      id: 'hero',
      type: 'hero',
      variant: 'editorial',
      kicker: 'Hair · Skin · Nails — Shoreditch, London',
      headline: ['Beauty,', 'edited.'],
      lead: 'A studio of eight chairs, four artists and one rule: nothing leaves this room unless it looks like you on your best day.',
      image: m.hero,
      secondaryImage: m.about,
      badges: ['Est. 2016', 'Members-first booking', 'Sunday openings'],
      stats: [
        { value: '4', label: 'Artists' },
        { value: '9k', label: 'Clients a year' },
        { value: '4.9', label: 'Rating' },
      ],
    },
    {
      id: 'ticker',
      type: 'marquee',
      items: [
        'Balayage',
        'Signature Facials',
        'Russian Manicure',
        'Brow Lamination',
        'Editorial Makeup',
        'Bridal',
        'Deep Tissue',
        'Lash Lift',
      ],
    },
    {
      id: 'about',
      type: 'split',
      variant: 'image-left',
      eyebrow: 'The studio',
      title: 'A small room, on purpose.',
      text: 'Lumé has eight chairs and no intention of adding a ninth. Every artist books their own column, so nobody is rushed and nothing is handed off halfway through. The result is a salon that feels less like a production line and more like a very good friend’s flat — if that friend happened to be a colourist.',
      image: m.about,
      secondaryImage: m.focus,
      signature: 'Isla Moreau · Creative Director',
      stat: { value: '8', label: 'chairs, and never more' },
      points: [
        {
          icon: 'palette',
          title: 'Consultation always comes first',
          text: 'Fifteen minutes, dry hair, honest advice — before anything is booked.',
        },
        {
          icon: 'leaf',
          title: 'Clean, cruelty-free products',
          text: 'Every line we stock is vegan and refill-first.',
        },
        {
          icon: 'crown',
          title: 'Members get the good slots',
          text: 'Saturday mornings open to members 48 hours early.',
        },
      ],
    },
    {
      id: 'services',
      type: 'services',
      variant: 'editorial',
      eyebrow: 'The menu',
      title: 'Services',
      text: 'Prices are honest starting points — your artist confirms the final figure at consultation, before anything begins.',
      showPrice: true,
      include: ['colour', 'cut', 'facial', 'nails'],
    },
    {
      id: 'treatments',
      type: 'services',
      variant: 'list',
      tone: 'alt',
      eyebrow: 'Also on the menu',
      title: 'Treatments',
      showPrice: true,
      include: ['massage', 'makeup', 'brows', 'bridal'],
    },
    {
      id: 'team',
      type: 'staff',
      variant: 'editorial',
      eyebrow: 'The artists',
      title: 'Four people, four waiting lists',
      text: 'Book the artist, not the salon. Each one keeps their own clients from first consultation onwards.',
    },
    {
      id: 'gallery',
      type: 'gallery',
      variant: 'masonry',
      eyebrow: 'The work',
      title: 'Recent from the floor',
      items: [
        { image: m.g1, caption: 'Soft copper balayage', span: 'tall' },
        { image: m.g5, caption: 'Blow-dry finish' },
        { image: m.g2, caption: 'Editorial makeup', span: 'wide' },
        { image: m.g6, caption: 'Almond gel set' },
        { image: m.g3, caption: 'Glass-skin facial' },
        { image: m.g7, caption: 'The retail wall' },
        { image: m.g4, caption: 'Bridal trial', span: 'tall' },
        { image: m.g8, caption: 'Treatment room' },
      ],
    },
    {
      id: 'membership',
      type: 'membership',
      tone: 'contrast',
      eyebrow: 'Membership',
      title: 'The Lumé Circle',
      text: 'For people who are in the chair often enough that it should cost less. Cancel any month, keep the credit.',
      tiers: [
        {
          name: 'Essential',
          price: 65,
          period: 'month',
          summary: 'For maintenance months.',
          perks: [
            '£75 studio credit each month',
            '10% off every treatment',
            'Priority waitlist access',
            'Complimentary fringe trims',
          ],
        },
        {
          name: 'Signature',
          price: 145,
          period: 'month',
          summary: 'The one most members choose.',
          featured: true,
          perks: [
            '£175 studio credit each month',
            '15% off every treatment',
            '48-hour early booking window',
            'One complimentary facial per quarter',
            'Members-only Sunday hours',
          ],
        },
        {
          name: 'Atelier',
          price: 320,
          period: 'month',
          summary: 'Colour, skin and nails, handled.',
          perks: [
            '£400 studio credit each month',
            '20% off every treatment',
            'Direct line to your artist',
            'Two guest passes a year',
            'Complimentary bridal trial',
          ],
        },
      ],
    },
    {
      id: 'reviews',
      type: 'testimonials',
      variant: 'carousel',
      eyebrow: 'Reviews',
      title: 'From the chair',
      items: [
        {
          name: 'Farrah Nazari',
          role: 'Colour client, 3 years',
          quote:
            'Isla is the only person who has ever asked what my hair does on day four. It changed everything about how I get it cut.',
          rating: 5,
        },
        {
          name: 'Céline Dubois',
          role: 'Signature member',
          quote:
            'I joined for the discount and stayed for the Sunday appointments. Nobody else in London will see me at 11am on a Sunday.',
          rating: 5,
        },
        {
          name: 'Nadia Okonkwo',
          role: 'Facial client',
          quote:
            'Talia fixed eight years of skin panic in three appointments and never once tried to sell me anything.',
          rating: 5,
        },
        {
          name: 'Rosa Milani',
          role: 'Bridal client',
          quote:
            'They gave us the whole back room, brought coffee, and I did not think about my hair once all day.',
          rating: 5,
        },
      ],
    },
    {
      id: 'book',
      type: 'cta',
      title: 'Chairs open two months ahead.',
      text: 'Choose your artist and your treatment, and take the slot before someone else does.',
      image: m.g2,
      note: 'No deposit. Free cancellation up to 24 hours before.',
    },
    {
      id: 'contact',
      type: 'contact',
      eyebrow: 'Find the courtyard',
      title: 'Shoreditch, London',
    },
  ],

  dashboard: {
    dailyVolume: 34,
    avgTicket: 128,
    customerLabel: 'Client',
    customerLabelPlural: 'Clients',
  },
};
